# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

class Rake::Task
  def abandon
    @actions.clear
  end
end

require 'tasks/rails'

# Ensures that seed data is loaded into database immediately after 'rake db:test:prepare' flushes it
namespace :db do
  namespace :test do
    task :prepare do
      Rake::Task['db:populate'].invoke
    end
  end
end
